<?
/*
Author: Artur `fhnb16` Tkachenko
2020
*/
header('Content-Type: text/html; charset=utf-8');

?>
<html>
<head>
    <?
    if(isset($PageTitle) && $PageTitle != "" && !empty($PageTitle) && $PageTitle != null){
        echo '<title>Nano CDS - '.$PageTitle.'</title>';
    }else{
        echo '<title>Nano CDS</title>';
    }
    ?>
    <!--
        Author: Artur `fhnb16` Tkachenko
        2020
    /-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body{background-color:#400f0f;background-image:radial-gradient(ellipse at top center,rgba(255,255,255,.1) 10%,rgba(255,255,255,0) 80%);color:white;font-family:"Motiva Sans",sans-serif}*,::after,::before{box-sizing:border-box;margin:0;padding:0}[tabindex="-1"]:focus:not(:focus-visible){outline:0!important}a{color:#007bff;text-decoration:none;background-color:transparent}a:hover{color:#0056b3}.group{display:-ms-flexbox;display:flex;-ms-flex-direction:column;flex-direction:column;border-radius:4px;padding:4px;margin:12px;background:linear-gradient(to right,rgba(0,0,0,.2) 0,rgba(0,0,0,.5) 100%)}.group-item-action{width:100%;color:#495057;text-align:inherit}.group-item-action:focus,.group-item-action:hover{z-index:1;color:lightgray;text-decoration:none;background:linear-gradient(180deg,rgb(155,65,65,.34) 0,rgb(245,103,103,.31) 100%)}.group-item-action:active{color:#212529;background-color:#e9ecef}.group-item{color:rgb(245,103,103,.88);position:relative;display:block;padding:.75rem 1.25rem;background:rgb(245,103,103,.10);border:1px solid rgba(0,0,0,.125)}.group-item:first-child{border-top-left-radius:inherit;border-top-right-radius:inherit}.group-item:last-child{border-bottom-right-radius:inherit;border-bottom-left-radius:inherit}.group-item.header,.group-item.footer{font-size:18px;color:#8f98a0;cursor:default;background:rgb(245,103,103,.19)}.group-item.header{cursor:default}.group-item.footer{cursor:hand}.group-item+.group-item{border-top-width:0}.container-fluid{-webkit-tap-highlight-color:transparent;text-align:left;box-sizing:border-box;width:100%;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}.btnv1{font-size:14px;font-weight:400;padding:2px 8px;display:inline-block;border-radius:6px;color:rgba(128,128,128,.8);text-decoration:none;background-color:transparent;border:1px dashed rgba(128,128,128,.8);transition:.32s border}.btnv1:hover{color:rgb(245,103,103,.88);text-decoration:none;border:1px solid rgb(245,103,103,.88);cursor:pointer}.btnv1:active{animation:flash .5s ease 1}@keyframes flash{0%{background:rgba(255,255,255,0)}20%{background:rgba(255,255,255,0.4)}}h2,p{margin:8px 24px}.color-grey{color:lightgrey}.color-info{color:lightblue}.color-warning{color:orange}.color-error{color:red}footer{text-align:center;padding:8px}footer>*{color:lightgray}.uppertext{text-transform:uppercase}.header>a,.header>span>a{color:#8f98a0}.header>a:hover,.header>span>a:hover{color:grey}.header>a:active,.header>span>a:active{color:lightgrey}
        .me{border: 1px dashed transparent;padding:2px;}.me:hover{border: 1px dashed rgba(128,128,128,.8);}.me:active{border: 1px dashed rgb(245,103,103,.88);}.form-control{display:block;width:100%;height:34px;padding:6px 12px;font-size:14px;line-height:1.42857143;color:white;background-color:transparent;background-image:none;border:1px dashed rgba(128,128,128,.8);border-radius:6px;-webkit-box-shadow:inset 0 1px 1px rgba(0,0,0,.075);box-shadow:inset 0 1px 1px rgba(0,0,0,.075);-webkit-transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;-o-transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;-webkit-transition:border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;transition:border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s;transition:border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s}.form-control:focus{border:1px solid rgb(245,103,103,.88);outline:0}.form-control::-moz-placeholder{color:#999;opacity:1}.form-control:-ms-input-placeholder{color:#999}.form-control::-webkit-input-placeholder{color:#999}.form-control::-ms-expand{background-color:transparent;border:0}.form-group{margin-bottom:15px}@media(min-width:768px){.form-inline .form-group{display:inline-block;margin-bottom:0;vertical-align:middle}.form-inline .form-control{display:inline-block;width:128px;vertical-align:middle;margin-bottom:4px}}.btn{display:inline-block;margin-bottom:0;font-weight:400;text-align:center;white-space:nowrap;vertical-align:middle;-ms-touch-action:manipulation;touch-action:manipulation;cursor:pointer;background-image:none;border:1px solid transparent;padding:6px 12px;font-size:14px;line-height:1.42857143;border-radius:4px;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.btn-default{font-size:14px;font-weight:400;display:inline-block;border-radius:6px;color:rgba(128,128,128,.8);text-decoration:none;background-color:transparent;border:1px dashed rgba(128,128,128,.8);transition:.32s border;margin-bottom:4px}.btn-default:hover{color:rgb(245,103,103,.88);text-decoration:none;border:1px solid rgb(245,103,103,.88);cursor:pointer}.btn-default:active{animation:flash .5s ease 1}@media(max-width:768px){.btn-default{width:100%}}.form-inline{padding:4px 20px}.form-control>option{color:black}.container{width:100%;box-sizing:border-box;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}@media(min-width:576px){.container{max-width:540px}}@media(min-width:768px){.container{max-width:720px;margin-top: 42px;}}@media(min-width:992px){.container{max-width:960px}}@media(min-width:1200px){.container{max-width:1140px}}.group{margin:6px}
        body{ overflow: overlay; } ::-webkit-scrollbar { height: 12px; width: 12px; z-index: 12; background: transparent; overflow: visible; } ::-webkit-scrollbar-track, ::-webkit-scrollbar-button { display: none; } ::-webkit-scrollbar-corner { background: rgb(67, 73, 83); } ::-webkit-scrollbar-thumb { width: 4px; min-height: 32px; z-index: 12; background-image: none; background-color: rgba(255, 255, 255,.128); background-clip: padding-box; border-width: 3px; border-style: solid; border-color: transparent; border-image: initial; border-radius: 10px; transition: background-color 0.32s ease-in-out 0s; } ::-webkit-scrollbar-thumb:hover { background-color: rgba(255, 255, 255,.256); } ::-webkit-scrollbar-track, ::-webkit-scrollbar-button { display: none; }
    </style>
</head>

<body>
    <div class="container">